version: "{build}"

image: Visual Studio 2022  # Adjust image based on your .NET version

build_script:
- ps: # Use PowerShell for these steps
  - $solutionPath = "$(SolutionDir)\name-sorter.sln"
  # Restore nuget packages for both projects
  NuGet restore $solutionPath
  # Build the test project first
  msbuild $solutionPath /p:Configuration=Release /target:Rebuild /property:TestProject=Tests
  # Build the main program project
  msbuild $solutionPath /p:Configuration=Release

after_build:
- ps: # Run tests after build
  $testResults = "$(BuildArtifactsDirectory)\**\*TestResults*.xml"
  if ($testResults) {
    Publish-TestResults -TestResultFiles $testResults -TestRunName "Name Sorter Tests"
  }
